Resources:
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue CrossStackVPC-VPCID
      CidrBlock: 10.1.10.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list       
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-A